development:
  adapter: mysql2
  database: blog_slave
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin

production_blog_master:
  adapter: mysql2
  database: blog_master
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
production_blog_slave:
  adapter: mysql2
  database: blog_slave
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
production_user_master:
  adapter: mysql2
  database: user_master
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
production_user_slave:
  adapter: mysql2
  database: user_slave
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
