development:
  adapter: mysql2
  database: user_master
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin

development_blog:
  adapter: mysql2
  database: blog_master
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
development_blog_slave:
  adapter: mysql2
  database: blog_slave
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
test_blog:
  adapter: mysql2
  database: blog_master_test
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
test_blog_slave:
  adapter: mysql2
  database: blog_slave
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin

development_user:
  adapter: mysql2
  database: user_master
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
development_user_slave:
  adapter: mysql2
  database: user_slave
  pool: 5
  username: root
  password: root
  timeout: 5000
  collation: utf8_bin
